name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    strategy:
      matrix:
        java: [ '11' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Barrel
          path: target/Barrel-1.0.0-SNAPSHOT.jar
          
      - name: Publishing new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Barrel
          body: |
            This is a development build of Barrel. Highly unstable!
            
            
            Triggered by ${{ github.sha }} at ${{ github.event.repository.updated_at }}
          #          files: |
          #            target/Barrel-1.0.0-SNAPSHOT.jar
          files: |
                  target/Barrel-1.0.0-SNAPSHOT.jar
